repos:
  - repo: local
    hooks:
      - id: swiftformat
        name: SwiftFormat
        entry: swiftformat --config .swiftformat .
        language: system
        types_or: [swift]
        pass_filenames: false
      - id: swiftlint
        name: SwiftLint
        entry: swiftlint --config .swiftlint.yml
        language: system
        types_or: [swift]
        pass_filenames: false