disabled_rules: []

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - single_test_class
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - vertical_parameter_alignment_on_call
  - yoda_condition

analyzer_rules:
  - explicit_self
  - unused_import

included:
  - VoltLift

excluded:
  - Carthage
  - Pods
  - DerivedData
  - build
  - .build
  - VoltLift/VoltLift.xcodeproj
  - VoltLift/VoltLift.xcodeproj/**
  - VoltLift/VoltLift.xcworkspace/**

allow_zero_lintable_files: true
strict: false
check_for_updates: true

force_cast: warning
force_try:
  severity: warning
force_unwrapping: error

line_length:
  warning: 120
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200

function_body_length:
  warning: 80
  error: 200

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  allowed_symbols: ["_"]

identifier_name:
  min_length:
    warning: 3
    error: 2
  excluded:
    - id
    - URL
    - x
    - y
    - i
    - j
    - s
    - m
    - l
    - xl
    - xxl
    - pill

custom_rules:
  avoid_todo_fixme:
    name: "Avoid TODO/FIXME in code"
    regex: "(TODO|FIXME)"
    match_kinds:
      - comment
    severity: warning

reporter: "xcode"


